name: Update Age

on:
  schedule:
    - cron: '0 0 30 4 *'
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate age
        id: calculate_age
        run: |
          current_year=$(date +'%Y')
          birth_year=2005
          age=$((current_year - birth_year))
          echo "::set-output name=age::$age"

      - name: Update README
        run: |
          sed -i "s/{age}/$(echo ${{ steps.calculate_age.outputs.age }})/" README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "[CHORE] Update age in README"
          git push