name: Update Age

on:
  schedule:
    - cron: '0 0 30 4 *'
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate age
        id: calculate_age
        run: |
          current_year=$(date +'%Y')
          birth_year=2005
          age=$((current_year - birth_year))
          echo "age=$age" >> $GITHUB_OUTPUT
          echo "old_age=$(( age - 1 ))" >> $GITHUB_OUTPUT

      - name: Update README
        env:
          AGE: ${{ steps.calculate_age.outputs.age }}
          OLD_AGE: ${{ steps.calculate_age.outputs.old_age }}
        run: |
          sed -i "s/<span>$OLD_AGE<span>/<age>$AGE<age>/" README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "[CHORE] Update age in README"
          git push
